server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  application:
    name: practice
app:
  storage:
    suspicious-directory: ./storage/suspicious